//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConquiánServidor.ConquiánDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int idGame { get; set; }
        public string rival { get; set; }
        public string gameTime { get; set; }
        public string result { get; set; }
        public string score { get; set; }
        public Nullable<int> idPlayer { get; set; }
        public Nullable<int> idGamemode { get; set; }
    
        public virtual Gamemode Gamemode { get; set; }
        public virtual Player Player { get; set; }
    }
}
