//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConquiánServidor.ConquiánDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestInvite
    {
        public int idInvitation { get; set; }
        public string email { get; set; }
        public string roomCode { get; set; }
        public System.DateTime creationDate { get; set; }
        public bool wasUsed { get; set; }
    }
}
