//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConquiánServidor.ConquiánDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lobby
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lobby()
        {
            this.Player1 = new HashSet<Player>();
        }
    
        public int idLobby { get; set; }
        public string roomCode { get; set; }
        public int idHostPlayer { get; set; }
        public int idStatusLobby { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<int> idGamemode { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual StatusLobby StatusLobby { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Player> Player1 { get; set; }
        public virtual Gamemode Gamemode { get; set; }
    }
}
